-- Carga idempotente del menu 2026 de Sierra Yara; solo afecta el slug sierra-yara.
do $$ declare s uuid;r record;x uuid;g uuid; begin select id into s from public.stores where slug='sierra-yara' limit 1;if s is null then raise exception 'No existe Sierra Yara.';end if;update public.stores set product_limit=greatest(coalesce(product_limit,0),129),updated_at=now() where id=s;create temp table syc(name text primary key,ord int,id uuid)on commit drop;insert into syc(name,ord)values ('CAFÉ',1),('CÓCTELES',2),('SMOOTHIES',3),('ICED COFFEE',4),('ICED TEA',5),('BATIDOS DE LA SIERRA',6),('LIMONADAS',7),('INFUSIONES',8),('BEBIDAS',9),('PANADERÍA',11),('POSTRES',12),('PASTELES',13),('GALLETAS',14),('CROISSANT, PANINNI & FOCACCIAS',15),('MENÚ SALUDABLE',16),('ENSALADAS',17),('APPETIZER',18),('PEPITOS',19),('BURGERS',20),('PLATOS FUERTES',21),('DESAYUNOS',22);for r in select * from syc loop select id into x from public.categories where store_id=s and lower(btrim(name))=lower(btrim(r.name)) order by created_at limit 1;if x is null then insert into public.categories(store_id,name,is_active,sort_order)values(s,r.name,true,r.ord)returning id into x;else update public.categories set name=r.name,is_active=true,sort_order=r.ord where id=x;end if;update syc set id=x where name=r.name;end loop;create temp table syp(cat text,name text,descr text,price numeric,ord int,id uuid,primary key(cat,name))on commit drop;insert into syp(cat,name,descr,price,ord)values ('CAFÉ','Espresso',null,1.80,1),
('CAFÉ','Americano',null,1.80,2),
('CAFÉ','Guayoyo',null,1.80,3),
('CAFÉ','Cortado',null,2.50,4),
('CAFÉ','Latte',null,3.20,5),
('CAFÉ','Latte Vainilla',null,3.20,6),
('CAFÉ','Latte Canela',null,3.20,7),
('CAFÉ','Bombón',null,3.50,8),
('CAFÉ','Mochacchino',null,3.70,9),
('CAFÉ','Mocha Nutella',null,4.50,10),
('CAFÉ','Chocolate Caliente',null,4.00,11),
('CAFÉ','Pistaccino',null,7.50,12),
('CÓCTELES','Aperol Spritz',null,9.50,1),
('CÓCTELES','Martini',null,7.00,2),
('CÓCTELES','Espresso Martini',null,6.00,3),
('CÓCTELES','Paloma de la Sierra',null,8.00,4),
('CÓCTELES','Tinto de Verano',null,6.00,5),
('CÓCTELES','Cheladas',null,2.50,6),
('CÓCTELES','Sierra Yara Mule',null,8.00,7),
('CÓCTELES','Moscow Mule',null,8.00,8),
('CÓCTELES','Margaritas',null,8.00,9),
('CÓCTELES','Mojitos',null,6.00,10),
('CÓCTELES','Cuba Libre',null,6.00,11),
('CÓCTELES','Gin & Tonic',null,6.00,12),
('CÓCTELES','Piña Colada',null,8.00,13),
('CÓCTELES','Mimosas',null,6.00,14),
('CÓCTELES','Daiquirí',null,6.00,15),
('SMOOTHIES','Fresa','Bebida cremosa a base de yogurt griego, leche condensada y fruta a elección.',4.50,1),
('SMOOTHIES','Mora','Bebida cremosa a base de yogurt griego, leche condensada y fruta a elección.',4.50,2),
('SMOOTHIES','Piña','Bebida cremosa a base de yogurt griego, leche condensada y fruta a elección.',4.50,3),
('SMOOTHIES','Parchita','Bebida cremosa a base de yogurt griego, leche condensada y fruta a elección.',4.50,4),
('SMOOTHIES','Durazno','Bebida cremosa a base de yogurt griego, leche condensada y fruta a elección.',4.50,5),
('ICED COFFEE','Frappuccino',null,5.50,1),
('ICED COFFEE','Dalgona',null,3.50,2),
('ICED COFFEE','Affogato',null,4.50,3),
('ICED COFFEE','Iced Latte',null,5.00,4),
('ICED COFFEE','Iced Caramel Latte',null,5.00,5),
('ICED COFFEE','Iced Latte Vainilla',null,5.00,6),
('ICED COFFEE','Iced MochaNutella',null,5.50,7),
('ICED COFFEE','Toddy',null,5.00,8),
('ICED TEA','Sierra Yara Iced Tea','Jengibre, té verde, miel, limón.',4.70,1),
('ICED TEA','Black Tea','Té negro, limón, hierba luisa, mandarina, jarabe de goma.',4.70,2),
('ICED TEA','Frutos Rojos Tea','Té frutos rojos, naranja, hierbabuena, jarabe de fresa mora.',4.70,3),
('ICED TEA','Citrus Tea','Té negro, naranja, parchita, hierbabuena.',4.70,4),
('BATIDOS DE LA SIERRA','Sierra','Guanábana, fresa, mandarina y jarabe de goma.',4.00,1),
('BATIDOS DE LA SIERRA','Citrus','Limón, naranja, mandarina y jarabe de goma.',4.00,2),
('BATIDOS DE LA SIERRA','Tropic Punch','Piña, mora, parchita, jarabe de goma.',4.00,3),
('LIMONADAS','Limonada Clásica','Hielo, limón y jarabe de goma.',3.00,1),
('LIMONADAS','Hierbabuena','Hielo, limón, hierbabuena y jarabe de goma.',3.00,2),
('LIMONADAS','Limonada de Coco','Hielo, limón, crema de coco, leche condensada y coco deshidratado.',3.50,3),
('LIMONADAS','Franchi Lemonade','Hielo, fresa, limón y jarabe de goma.',3.50,4),
('LIMONADAS','Sparkling Lemonade','Hielo, soda de fresa, limón, hierbabuena y jarabe de goma.',4.00,5),
('LIMONADAS','Yara Lemonade','Soda de toronja, fresa, limón y jarabe de goma.',5.00,6),
('INFUSIONES','Sierra Yara',null,2.00,1),
('INFUSIONES','Manzanilla',null,2.00,2),
('INFUSIONES','Té Verde',null,2.00,3),
('INFUSIONES','Té Negro',null,2.00,4),
('INFUSIONES','Té de Jamaica',null,2.00,5),
('INFUSIONES','Sierra Yara Hot Tea',null,4.00,6),
('INFUSIONES','Honey Tea',null,4.00,7),
('BEBIDAS','Agua',null,1.80,1),
('BEBIDAS','Refresco',null,3.00,2),
('BEBIDAS','Sparkling',null,3.00,3),
('PANADERÍA','Cachito de Jamón y Tocineta',null,3.20,1),
('PANADERÍA','Cachito de Jamón y Queso Crema',null,4.00,2),
('PANADERÍA','Cachito de Jamón de Pavo',null,3.20,3),
('PANADERÍA','Cachitos de Mortadela Pistacho',null,3.20,4),
('PANADERÍA','Cachito Sierra',null,4.50,5),
('PANADERÍA','Pan de Queso',null,3.00,6),
('POSTRES','Cinnamon Roll',null,4.50,1),
('POSTRES','Brookie',null,3.00,2),
('POSTRES','Tres Leche',null,4.50,3),
('POSTRES','Tiramisú',null,5.60,4),
('POSTRES','Mousse de Chocolate',null,5.00,5),
('POSTRES','Cheesecake de Fresa',null,7.50,6),
('POSTRES','Cheesecake de Nutella',null,7.50,7),
('POSTRES','Cheesecake de Pistacho',null,10.50,8),
('POSTRES','Cheesecake de Arequipe',null,7.50,9),
('POSTRES','Brownie con Helado',null,4.50,10),
('PASTELES','Tronchatoro',null,6.00,1),
('PASTELES','Zanahoria',null,5.80,2),
('PASTELES','Choco Red Velvet',null,5.50,3),
('PASTELES','Limón Amapola',null,5.00,4),
('PASTELES','Choco-Arequipe',null,5.00,5),
('PASTELES','Banana Cake',null,5.00,6),
('PASTELES','Orange BlueBerry',null,5.00,7),
('PASTELES','Lingote de Limón',null,5.00,8),
('GALLETAS','Mix 6 Galletas Surtidas',null,4.50,1),
('GALLETAS','NY Style Nutella',null,6.00,2),
('GALLETAS','NY Style Avellana',null,4.70,3),
('GALLETAS','Signature Premiun',null,5.50,4),
('GALLETAS','Crumble Cookie',null,5.50,5),
('CROISSANT, PANINNI & FOCACCIAS','Preferito dello chef','Jamón coppa di parma, tomate, lechuga fresca, aceite de oliva, parmigiano reggiano y mayo anchoas.',11.00,1),
('CROISSANT, PANINNI & FOCACCIAS','Francesco','Jamón serrano, queso holandés y aceite de oliva.',11.00,2),
('CROISSANT, PANINNI & FOCACCIAS','Luigi','Mortadela pistaccio, queso holandés, tomate fresco y aceite de oliva.',11.00,3),
('CROISSANT, PANINNI & FOCACCIAS','Sierra','Jamón de pierna, queso holandés y mayonesa plain.',9.00,4),
('CROISSANT, PANINNI & FOCACCIAS','Mariana','Jamón coppa di parma, queso holandés, rúcula, tomates frescos y mayo-sriracha.',11.00,5),
('CROISSANT, PANINNI & FOCACCIAS','Tre Formaggio','Jamón coppa di parma, queso holandés, queso parmigiano reggiano.',11.00,6),
('CROISSANT, PANINNI & FOCACCIAS','Italianissima','Mortadela pistaccio, straciatella, tomates frescos, pesto y pistaccio.',11.00,7),
('CROISSANT, PANINNI & FOCACCIAS','Zue','Jamón, queso, tomate y lechuga.',9.00,8),
('CROISSANT, PANINNI & FOCACCIAS','Coppa Di Parma','Mozzarella, tomate fresco, pesto de la casa y jamón coppa di parma.',11.00,9),
('CROISSANT, PANINNI & FOCACCIAS','Serrano','Tomates confitados, aceite de oliva, jamón serrano y mayo aceituna.',10.00,10),
('CROISSANT, PANINNI & FOCACCIAS','Sebita','Nutella, fresa y azúcar glass.',8.50,11),
('MENÚ SALUDABLE','Parfait','Nutritivo parfait con yogurt griego artesanal, frutas (kiwi, fresa, arándano, durazno), granola, nuez, almendra y miel.',7.00,1),
('MENÚ SALUDABLE','Sándwich Clásico','Nuestro clásico de jamón de pierna, queso holandés y aceite de oliva.',5.00,2),
('MENÚ SALUDABLE','Sándwich de Pavo','Delicioso sándwich con jamón de pavo, rúcula, queso paisa, tomate seco y aceite de oliva.',6.00,3),
('MENÚ SALUDABLE','Sándwich de Atún','Fresco sándwich de atún, yogurt, pesto, tomate, aceituna y rúcula.',8.00,4),
('ENSALADAS','ORL','Especialidad del chef, exquisita ensalada César con aderezo secreto de la casa, pollo a la plancha o crispy, lechuga y rúcula, parmigiano reggiano, jamón coppa di parma y crotones.',12.00,1),
('ENSALADAS','Zue','Mix de rúcula y lechuga, tomate, mozzarella, almendra, pollo, pesto y crotones.',12.00,2),
('ENSALADAS','Sierra','Fresco mix de lechuga y rúcula, aguacate, yogurt agrio, tomate cherry, pollo salteado con cebolla y champiñones.',12.00,3),
('APPETIZER','Alitas','Crujientes y deliciosas alitas de pollo estilo americano cargadas de mucho sabor, salteadas en cualquiera de nuestras salsas.',8.00,1),
('APPETIZER','Capitan Pops','Deliciosos cuadros de pollo súper crujientes llenos de sabor en cualquiera de nuestras salsas.',7.00,2),
('APPETIZER','Tequeños Bites','Diez (10) deliciosos tequeños rellenos de full queso, acompañados de salsa de ajo del capitán.',8.00,3),
('APPETIZER','Papas Fritas','350gr de crocante y deliciosas papas a la francesa.',4.00,4),
('PEPITOS','Guaro','Blend de carne entre solomo, lomito asado y punta de res, sobre un pan campesino de concha dura, salsa de ajo asados del capitán, ketchup, queso facilista, queso mozzarella, gouda, parmigiano y tocineta crujiente.',14.00,1),
('PEPITOS','Brangus','Clásico pepito relleno de lechuga, tomate, cebolla, papa rallada, queso facilista, tocino y aderezo del capitán.',14.00,2),
('PEPITOS','Chicken Crispy','Mix de lechuga y rúcula, tomate, aderezo césar, pollo súper crujiente, queso facilista, parmigiano y tocino.',14.00,3),
('BURGERS','Bacon Star','Nuestro Best Seller, pan de la casa, rúcula, pepinillos, carne F1, doble queso cheddar, tocino, tomate y mayo-sriracha.',11.00,1),
('BURGERS','Crispy ORL','Deliciosa burger agridulce, servida en pan brioche, lechuga, pepinillos, doble queso cheddar y tocino; con pollo crispy glaseado en nuestra exquisita salsa ORL.',12.00,2),
('BURGERS','Spicy Burger','Pan de la casa, lechuga, jalapeños, aderezo de la casa, carne F1 con cerdo y ají rocoto asado, queso mozzarella, tomate y mayo-sriracha.',11.00,3),
('BURGERS','Capitán Burger','Disfruta y déjate cautivar con nuestra carne de especialidad F1 capitán, ahumada, jugosa y tierna. Servida en vegetales frescos, papa rayada, salsas de la casa y queso cheddar.',11.00,4),
('BURGERS','Capitán F1','Clásica burger con papa rallada, lechuga, tomate, cebolla, pepinillos, queso cheddar y 150gr de solomo picado.',11.00,5),
('PLATOS FUERTES','Pasta Boloñesa','Lento, fresco & sustancioso ragú de res en salsa pomodoro guisada con su toque de vino tinto, gratinada con mozzarella.',16.00,1),
('PLATOS FUERTES','Pasta Carbonara á la Sierra','Rigatones a la crema en salsa bechamel, pollo, mantequilla, tocino y una crujiente corona de parmigiano reggiano.',16.00,2),
('DESAYUNOS','Croque Madame','Rebanadas de pan brioche con clásica bechamel, jamón ahumado, queso emmental, mozzarella gratinado y huevo estrellado a elección.',11.00,1),
('DESAYUNOS','Croque Monsieur','Clásico parisino en pan brioche, relleno de jamón ahumado, queso emmental, bechamel, mozzarella gratinado y polvo de tocineta.',8.00,2),
('DESAYUNOS','Desayuno Americano','Panqueques o pan, huevos, tocino, jamón, queso, sirope o mantequilla.',7.00,3),
('DESAYUNOS','Desayuno Sierra Yara','Arepa de tu preferencia, caraotas de la abuela, proteína de tu preferencia (pollo, carne mechada o molida), huevo y queso blanco.',8.00,4),
('DESAYUNOS','Huevos Cremosos','Deliciosos huevos revueltos, cremosos, acompañados de tocino, aguacate y tostadas de pan.',7.00,5);for r in select * from syp loop select p.id into x from public.products p join syc c on c.id=p.category_id where p.store_id=s and c.name=r.cat and lower(btrim(p.name))=lower(btrim(r.name)) order by p.created_at limit 1;if x is null then insert into public.products(store_id,category_id,name,description,price_usd,discount_percent,image_url,is_available,is_featured,sort_order)values(s,(select id from syc where name=r.cat),r.name,r.descr,r.price,0,null,true,false,r.ord)returning id into x;else update public.products set category_id=(select id from syc where name=r.cat),name=r.name,description=r.descr,price_usd=r.price,discount_percent=0,is_available=true,is_featured=false,sort_order=r.ord,updated_at=now() where id=x;end if;update syp set id=x where cat=r.cat and name=r.name;end loop;create temp table syg(k text primary key,name text,descr text,req boolean,mi int,ma int,ord int,id uuid)on commit drop;insert into syg values('milk','Tipo de leche','Puedes cambiar el tipo de leche.',false,0,1,1,null),('sauce','Salsa','Selecciona una salsa incluida.',true,1,1,2,null),('style','Presentación','Selecciona cómo deseas tu hamburguesa.',true,1,1,3,null),('term','Término de cocción','Selecciona el término de cocción.',true,1,1,4,null);for r in select * from syg loop select id into g from public.product_option_groups where store_id=s and lower(btrim(name))=lower(btrim(r.name)) order by created_at limit 1;if g is null then insert into public.product_option_groups(store_id,name,description,selection_type,required,min_select,max_select,is_active,sort_order)values(s,r.name,r.descr,'single',r.req,r.mi,r.ma,true,r.ord)returning id into g;else update public.product_option_groups set name=r.name,description=r.descr,selection_type='single',required=r.req,min_select=r.mi,max_select=r.ma,is_active=true,sort_order=r.ord,updated_at=now()where id=g;end if;update syg set id=g where k=r.k;end loop;create temp table syo(k text,name text,descr text,price numeric,ord int,primary key(k,name))on commit drop;insert into syo values('milk','Descremada',null,.5,1),('milk','Almendra',null,.5,2),('sauce','ORL','Sabor dulce y ahumado a base de mermelada de fresa y mantequilla de maní.',0,1),('sauce','HONEY','Tradicional salsa miel y mostaza con un toque especial del chef.',0,2),('sauce','BUFFALO NY','Picante a base de mantequilla y tabasco.',0,3),('sauce','SALSA DE TAMARINDO','Reducción de tamarindo y salsas chinas.',0,4),('sauce','CHUTNEY DE PIÑA','Cuadros de piña asada con toque de miel y canela.',0,5),('sauce','PASIÓN NARANJA','Salsa de naranja, parchita, chile picante y paprika.',0,6),('sauce','SALSA AGRIDULCE','Salsa dulce, agria y ácida.',0,7),('style','Con pan',null,0,1),('style','Al plato (sin pan)',null,0,2),('term','Medio',null,0,1),('term','Tres cuartos',null,0,2),('term','Bien cocida',null,0,3);for r in select o.*,y.id gid from syo o join syg y using(k) loop if exists(select 1 from public.product_option_values where option_group_id=r.gid and lower(btrim(name))=lower(btrim(r.name)))then update public.product_option_values set name=r.name,description=r.descr,price_delta_usd=r.price,is_active=true,sort_order=r.ord,updated_at=now()where option_group_id=r.gid and lower(btrim(name))=lower(btrim(r.name));else insert into public.product_option_values(option_group_id,name,description,price_delta_usd,is_active,sort_order)values(r.gid,r.name,r.descr,r.price,true,r.ord);end if;end loop;create temp table syl(k text,cat text,name text,ord int,primary key(k,cat,name))on commit drop;insert into syl values('milk','CAFÉ','Cortado',1),('milk','CAFÉ','Latte',1),('milk','CAFÉ','Latte Vainilla',1),('milk','CAFÉ','Latte Canela',1),('milk','CAFÉ','Bombón',1),('milk','CAFÉ','Mochacchino',1),('milk','CAFÉ','Mocha Nutella',1),('milk','CAFÉ','Chocolate Caliente',1),('milk','CAFÉ','Pistaccino',1),('sauce','APPETIZER','Alitas',1),('sauce','APPETIZER','Capitan Pops',1),('style','BURGERS','Bacon Star',1),('style','BURGERS','Crispy ORL',1),('style','BURGERS','Spicy Burger',1),('style','BURGERS','Capitán Burger',1),('style','BURGERS','Capitán F1',1),('term','BURGERS','Bacon Star',2),('term','BURGERS','Spicy Burger',2),('term','BURGERS','Capitán Burger',2),('term','BURGERS','Capitán F1',2);for r in select l.*,y.id gid,p.id pid from syl l join syg y using(k)join syp p on p.cat=l.cat and p.name=l.name loop insert into public.product_option_group_products(store_id,product_id,option_group_id,sort_order)values(s,r.pid,r.gid,r.ord)on conflict(product_id,option_group_id)do update set store_id=excluded.store_id,sort_order=excluded.sort_order,updated_at=now();end loop;end $$;
